apiVersion: v1
stringData:
  outscalecredentialConfig-accessKey: {{ .Values.access_key }}
  outscalecredentialConfig-region: {{ .Values.region }}
  outscalecredentialConfig-secretKey: {{ .Values.secret_key }}
kind: Secret
metadata:
  name: {{ .Values.cloudCredentialSecretName }}
  namespace: cattle-global-data
type: Opaque